config/routes.rb
Sqooz::Application.routes.draw do

  

  
  resources :request_invites, :only => [:new, :create]

  get "paid/sqoozers" => "static#paid_sqoozers", :as => :paid_sqoozer
  match "samples/email" => "static#send_sample_email", :as => :send_sample_email, via: [:get, :post]
  post "suggest_interest" => "interests#suggest", :as => :suggest_interest
  get "recommended(/:page)" => "feed#recommended", :as => :feed, constraints: { page: /\d+/ }

  get "search/(:page)" => "pages#search", :as => :search

  get "feed/activity(/:page)" => "feed#activity", :as => :feed_activity, constraints: { page: /\d+/ }
  get "trending(/:page)" => "feed#trending", :as => :feed_trending, constraints: { page: /\d+/ }
  get "feed/lists(/:page)" => "feed#lists", :as => :feed_list, constraints: { page: /\d+/ }
  get "feed/channels(/:page)" => "feed#channels", :as => :feed_channels, constraints: { page: /\d+/ }
  get "social/page/:id" => "pages#share_page", :as => :share_page
  devise_for :users

  resources :interests, :only => [:create, :destroy, :index]
  get "interest/:id/(/:page)"  => "interests#show", :as => :show_interest, constraints: { page: /\d+/ }
  get "tag/:name/(/:page)"  => "tags#show", :as => :show_tag, constraints: { page: /\d+/ }
  get "tags/(/:page)"  => "tags#index", :as => :tags, constraints: { page: /\d+/ }
  get "top/sqoozers(/:page)" => "discover#top_users", :as => :top_users, constraints: { page: /\d+/ }
  get "top/channels(/:page)" => "discover#top_channels", :as => :top_channels, constraints: { page: /\d+/ }
  resources :users do
    member do
      get "following/lists(/:page)"  => "users#following_lists", :as => :following_lists, constraints: { page: /\d+/ }
      get "following/channels(/:page)"  => "users#following_channels", :as => :following_channels, constraints: { page: /\d+/ }
      get "following(/:page)"  => "users#following", :as => :following, constraints: { page: /\d+/ }
     
      get "followers(/:page)"  => "users#followers", :as => :followers, constraints: { page: /\d+/ }
      get "interests(/:page)"  => "users#interests", :as => :interests, constraints: { page: /\d+/ }
      get "history(/:page)"  => "users#history", :as => :history, constraints: { page: /\d+/ }
      get "lists(/:page)"  => "users#lists", :as => :lists, constraints: { page: /\d+/ }
      get "comments(/:page)"  => "users#comments", :as => :comments, constraints: { page: /\d+/ }
      get "channels(/:page)"  => "users#channels", :as => :channels, constraints: { page: /\d+/ }
      get "notifications(/:page)"  => "users#notifications", :as => :notifications, constraints: { page: /\d+/ }
      get "likes(/:page)"  => "users#likes", :as => :likes,  constraints: {page: /\d+/}
      get "likes/filter/:filter(/:page)" => "users#likes", :as => :likes_ptype, constraints: { page: /\d+/ }
      get "likes/interest/:iname(/:page)" => "users#likes", :as => :likes_interest, constraints: { page: /\d+/ }
       get "likes/channel/:cname(/:page)" => "users#likes", :as => :likes_channel, constraints: { page: /\d+/ }
      get "pages(/:page)"  => "users#pages", :as => :pages,  constraints: {page: /\d+/}
      get "pages/list/:filter(/:page)" => "users#pages", :as => :pages_ptype, constraints: { page: /\d+/ }
      get "pages/interest/:iname(/:page)" => "users#pages", :as => :pages_interest, constraints: { page: /\d+/ }
      get "pages/channel/:cname(/:page)" => "users#pages", :as => :pages_channel, constraints: { page: /\d+/ }
    end

    collection do
      post "report_page" => "users#report", :as => :report
    end
  end

  post "follow" => "users#follow", :as => :follow

  resources :channels, :only => [:new, :edit,:create, :index, :show]
  resources :listings, :only => [:create, :destroy, :index]
  resources :comments, :only => [:create, :destroy, :index]
  resources :lists, :only => [:create, :destroy, :index]
  resources :likes, :only => [:create, :destroy]
  resources :pages, :only => [:create, :new, :edit, :update, :destroy] do
    member do
      get "about"
      post "about"
    end
    collection do
      post "photo/upload" => "pages#medium_photo_upload"
      post "photo/delete" => "pages#medium_photo_delete"
    end
  end

  post "pages/sqooz" => "pages#sqoozme", :as => :sqoozit
  get "sqoozing" => "pages#sqoozme", :as => :sqoozit_ad
  get "video/:sitename/:id" => "pages#show", :as => :video_show, :constraints => { :sitename => /[^\/]*/, :id => /[^\/]*/ }
  get "page/:id" => "pages#show", :as => :page_show, :constraints => { :sitename => /[^\/]*/, :id => /[^\/]*/ }
  get "about" => "static#about"
  get "help" => "static#help"
  get "discover/interests(/:page)" => "discover#interests", :as => :discover_interests
  get "discover/channels(/:page)" => "discover#channels", :as => :discover_channels

  root :to => 'static#welcome'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  belongs_to :user
  acts_as_followable
  has_many :pages
  counter_culture :user

  extend FriendlyId
  friendly_id :title, use: :slugged


  validates :title, presence: true
  validates :about, presence: true

  has_attached_file :cover_photo, :styles => { :thumb => "75x75#", 
    :medium => "440>x" }, :convert_options => {
    :medium => "-quality 45 -strip", :thumb => "-quality 45 -strip", :original => "-quality 50 -strip" }, :default_url =>  ":default_image_url"
  
   
  validates_attachment_content_type :cover_photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  before_filter :authenticate_user!

  def new
    @channel = current_user.channels.build
  end

  def edit
  end

  def show
   @channel = Channel.friendly.find(params[:id])
   if @channel
    @pages = @channel.pages.page(params[:page] || 1).includes(:interest)
    respond_to do |format|
      format.html {render "channel.html.erb"}
      format.js { render "channel_xhr.html.erb", :layout => false, :status => 200 }
    end
   else
    not_found
   end
  end

  def create
    @channel = current_user.channels.build(channel_params)
    respond_to do |format|
      if @channel.save
        format.html { redirect_to new_page_path, notice: 'Channle successfully created.' }
        format.json { render action: 'show', status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end
private
  def channel_params
    params.require(:channel).permit!
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channel.html.erb
<div class="channel-container"> 
  <div class="media">
     <%= link_to image_tag(channel.user.avatar(:thumb), :class => "media-object").html_safe, user_path(channel.user), :alt => channel.user.username, :class => "pull-left" %>
    <div class="media-body">
      <h3 class="media-heading"><%= link_to channel.user.username , user_path(channel.user), :class => "special-hover-link" %></h3>
      <ul class="list-inline">
        <li>
          <%= link_to "#{channel.user.likes_count} Likes".html_safe, likes_user_path(channel.user) %>
        </li>
        <li>
          <%= link_to "#{channel.user.pages_count} Pages".html_safe, pages_user_path(channel.user) %>
        </li>
      
        <li>
          <%= link_to "#{channel.user.comments_count} Comments".html_safe, comments_user_path(channel.user) %>
        </li>

        <li>
          <%= link_to "#{channel.user.comments_count} Comments".html_safe, comments_user_path(channel.user) %>
        </li>
        
      </ul>
    </div>
  </div>     
  <!-- <div id="my-sqooz-show-page">
    <div class="row margin-0" id="frame-container"> -->
      <!-- <div class="margin-0 padding-0 col-xs-12 col-sm-12 text-center"> -->
        <!-- <div id="my-splash-box" style="background: transparent;"> -->
          
          <%= link_to (image_tag channel.cover_photo(:medium)).html_safe, channel_path(channel) %>
         <!--  <div class="splash-image cover-image" style="background-image: url('<%= request.protocol +  request.host_with_port + channel.cover_photo.url %>')" class="cover-image"></div> -->
          <div class="splash-content">
            <div class="alpha-static">
              <h3 class="margin-0"><%= link_to channel.title, channel_path(channel) %></h3>
              <p class="margin-0">Created by: <%= link_to channel.user.username, user_path(channel.user) %></p>
              <ul class="list-inline margin-bottom-0">
                <li>
                  <%= channel.followers_counter %> Followers
                </li>
                <li>
                  <%= channel.pages_count %> Pages
                </li>
                <% unless @following_ids.nil? %>
                <li>
                  <%= follow_unfollow_small_link("Channel", channel.id, !@following_ids.include?(channel.id), "pull-right") %>
                </li> 
                <% end %>
              </ul>
            </div>
          </div>
       <!--  </div> -->
      <!-- </div> -->
    <!-- </div>
    
  </div> -->
</div>

app/views/channels/_form.html.erb
<% if @channel.errors.any? %>
    
    <div id="error_explanation" class="alert alert-danger">
      <h3 class="margin-top-0"><%= pluralize(@channel.errors.count, "error") %> prohibited this task from being saved:</h3>
      <ul class="list-unstyled">
      <% @channel.errors.full_messages.each do |msg| %>
        <li class="text-danger"><%= msg %></li>
      <% end %>
      </ul>
    </div>

<% end %>

<%= form_for @channel, :html => {:multipart => true, :class => "white-box form-horizontal page-form", :role => "form"} do |f| %>
    <div class="form-group">
      <h1 class="text-center">Create a Channel</h1>
    </div>
    
    <div class="form-group">
      <div class="col-sm-10 col-sm-offset-1">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, :class => "form-control", :placeholder => "Title" %>
      </div>
    </div>
    
    
    
    <div class="form-group margin-bottom-0">
      <div class="col-sm-10 col-sm-offset-1">
        <%= f.label :about, "Write about the channel" %>
        <%= f.text_area :about, :class => "form-control", :placeholder => "Write about the channel" %>
      </div>
      
    </div>

    <div class="form-group" id="image-upload">
      <div class="col-sm-10 col-sm-offset-1">
        <%= f.label :cover_photo, "Cover Image" %>
        <%= f.file_field :cover_photo, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group margin-top-10">
      <div class="col-sm-10 col-sm-offset-1">
        <% if @channel.new_record? %>
          <%= f.submit "Create", :class => "btn btn-primary pull-right" %>
        <% else %>
          <%= f.submit "Update", :class => "btn btn-primary pull-right" %>
        <% end %>
      </div>
    </div>
    
<% end %>

app/views/channels/channel.html.erb
<div class="container-fluid margin-0 padding-0" id="my-sqooz-show-page">
  <div class="row margin-0" id="frame-container">
    <div class="margin-0 padding-0 col-xs-12 col-sm-12 text-center">
      <div id="my-splash-box">
        
        <div class="bluring"></div>
        <div class="overlay-light"></div>
        <div id="splash-image" style="background-image: url('<%= request.protocol + request.host_with_port + @channel.cover_photo(:original) %>')" class="cover-image"></div>
        <div id="splash-content" class="padding-20" style="bottom: 0px; top: auto;">
          <h1 class="margin-0"><%= @channel.title %></h1>
          <p class="margin-0"><%= link_to @channel.user.username, user_path(@channel.user) %></p>
          <ul class="list-inline margin-bottom-0">
            <li>
              <%= @channel.followers_counter %> Followers
            </li>
            <li>
              <%= @channel.pages_count %> Pages
            </li>
            <% unless @following_ids.nil? %>
            <li>
              <%= follow_unfollow_small_link("Channel", @channel.id, !@following_ids.include?(@channel.id), "pull-right") %>
            </li> 
            <% end %>
          </ul>
          <p>
            <%= truncate(@channel.about, :length => 600) %>
          </p>
        </div>
      </div>
    </div>
  </div>
  
</div>

<div class="container margin-top-30" >
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 "> 
      <ul class="list-unstyled" id="my-list-container">   
        <%= render partial: "pages/page_list", collection: @pages, :as => :page %>
      </ul>
    </div>
  </div>
  <%= link_to_next_page @pages, 'Next Page', :class => "hide" %>
</div>

app/views/channels/create.html.erb
<h1>Channels#create</h1>
<p>Find me in app/views/channels/create.html.erb</p>

app/views/channels/edit.html.erb
<h1>Channels#edit</h1>
<p>Find me in app/views/channels/edit.html.erb</p>

app/views/channels/new.html.erb
<% content_for :title, "Add a channel on #{SITENAME}" %>
<% content_for :description, "Add channels and pages of different interests #{SITENAME}"  %>
<div class="container" id="new-page-container">
  <div class="row">
    <%= render "form.html.erb" %>
  </div>
</div>

app/views/channels/update.html.erb
<h1>Channels#update</h1>
<p>Find me in app/views/channels/update.html.erb</p>