config/routes.rb
Sqooz::Application.routes.draw do

  

  
  resources :request_invites, :only => [:new, :create]

  get "paid/sqoozers" => "static#paid_sqoozers", :as => :paid_sqoozer
  match "samples/email" => "static#send_sample_email", :as => :send_sample_email, via: [:get, :post]
  post "suggest_interest" => "interests#suggest", :as => :suggest_interest
  get "recommended(/:page)" => "feed#recommended", :as => :feed, constraints: { page: /\d+/ }

  get "search/(:page)" => "pages#search", :as => :search

  get "feed/activity(/:page)" => "feed#activity", :as => :feed_activity, constraints: { page: /\d+/ }
  get "trending(/:page)" => "feed#trending", :as => :feed_trending, constraints: { page: /\d+/ }
  get "feed/lists(/:page)" => "feed#lists", :as => :feed_list, constraints: { page: /\d+/ }
  get "feed/channels(/:page)" => "feed#channels", :as => :feed_channels, constraints: { page: /\d+/ }
  get "social/page/:id" => "pages#share_page", :as => :share_page
  devise_for :users

  resources :interests, :only => [:create, :destroy, :index]
  get "interest/:id/(/:page)"  => "interests#show", :as => :show_interest, constraints: { page: /\d+/ }
  get "tag/:name/(/:page)"  => "tags#show", :as => :show_tag, constraints: { page: /\d+/ }
  get "tags/(/:page)"  => "tags#index", :as => :tags, constraints: { page: /\d+/ }
  get "top/sqoozers(/:page)" => "discover#top_users", :as => :top_users, constraints: { page: /\d+/ }
  get "top/channels(/:page)" => "discover#top_channels", :as => :top_channels, constraints: { page: /\d+/ }
  resources :users do
    member do
      get "following/lists(/:page)"  => "users#following_lists", :as => :following_lists, constraints: { page: /\d+/ }
      get "following/channels(/:page)"  => "users#following_channels", :as => :following_channels, constraints: { page: /\d+/ }
      get "following(/:page)"  => "users#following", :as => :following, constraints: { page: /\d+/ }
     
      get "followers(/:page)"  => "users#followers", :as => :followers, constraints: { page: /\d+/ }
      get "interests(/:page)"  => "users#interests", :as => :interests, constraints: { page: /\d+/ }
      get "history(/:page)"  => "users#history", :as => :history, constraints: { page: /\d+/ }
      get "lists(/:page)"  => "users#lists", :as => :lists, constraints: { page: /\d+/ }
      get "comments(/:page)"  => "users#comments", :as => :comments, constraints: { page: /\d+/ }
      get "channels(/:page)"  => "users#channels", :as => :channels, constraints: { page: /\d+/ }
      get "notifications(/:page)"  => "users#notifications", :as => :notifications, constraints: { page: /\d+/ }
      get "likes(/:page)"  => "users#likes", :as => :likes,  constraints: {page: /\d+/}
      get "likes/filter/:filter(/:page)" => "users#likes", :as => :likes_ptype, constraints: { page: /\d+/ }
      get "likes/interest/:iname(/:page)" => "users#likes", :as => :likes_interest, constraints: { page: /\d+/ }
       get "likes/channel/:cname(/:page)" => "users#likes", :as => :likes_channel, constraints: { page: /\d+/ }
      get "pages(/:page)"  => "users#pages", :as => :pages,  constraints: {page: /\d+/}
      get "pages/list/:filter(/:page)" => "users#pages", :as => :pages_ptype, constraints: { page: /\d+/ }
      get "pages/interest/:iname(/:page)" => "users#pages", :as => :pages_interest, constraints: { page: /\d+/ }
      get "pages/channel/:cname(/:page)" => "users#pages", :as => :pages_channel, constraints: { page: /\d+/ }
    end

    collection do
      post "report_page" => "users#report", :as => :report
    end
  end

  post "follow" => "users#follow", :as => :follow

  resources :channels, :only => [:new, :edit,:create, :index, :show]
  resources :listings, :only => [:create, :destroy, :index]
  resources :comments, :only => [:create, :destroy, :index]
  resources :lists, :only => [:create, :destroy, :index]
  resources :likes, :only => [:create, :destroy]
  resources :pages, :only => [:create, :new, :edit, :update, :destroy] do
    member do
      get "about"
      post "about"
    end
    collection do
      post "photo/upload" => "pages#medium_photo_upload"
      post "photo/delete" => "pages#medium_photo_delete"
    end
  end

  post "pages/sqooz" => "pages#sqoozme", :as => :sqoozit
  get "sqoozing" => "pages#sqoozme", :as => :sqoozit_ad
  get "video/:sitename/:id" => "pages#show", :as => :video_show, :constraints => { :sitename => /[^\/]*/, :id => /[^\/]*/ }
  get "page/:id" => "pages#show", :as => :page_show, :constraints => { :sitename => /[^\/]*/, :id => /[^\/]*/ }
  get "about" => "static#about"
  get "help" => "static#help"
  get "discover/interests(/:page)" => "discover#interests", :as => :discover_interests
  get "discover/channels(/:page)" => "discover#channels", :as => :discover_channels

  root :to => 'static#welcome'

end

app/models/request_invite.rb
class RequestInvite < ActiveRecord::Base


  def invite(invite_for_job=false)
    rinvite = self
    ActiveRecord::Base.transaction do
      User.invite!(:email => self.email, :username => self.name , :author => self.author, :paid => self.paid, :invite_for_job => invite_for_job)
      rinvite.update_attributes(:invite_sent => true, :invite_sent_at => Time.now)
    end
  end
end

app/controllers/request_invites_controller.rb
class RequestInvitesController < ApplicationController
  before_action :set_request_invite, only: [:show, :edit, :update, :destroy]

  # GET /request_invites
  # def index
  #   @request_invites = RequestInvite.all
  # end

  # GET /request_invites/1
  def show
  end

  # GET /request_invites/new
  def new
    @request_invite = RequestInvite.new
  end

  # GET /request_invites/1/edit
  def edit
    not_found
  end

  # POST /request_invites
  def create
    @request_invite = RequestInvite.new(request_invite_params)

    if @request_invite.save
      begin
        Notifier.invite_request(@request_invite).deliver
      rescue Exception => e
        logger.error "Could not send email: #{e.message}"
      end
      redirect_to root_path, notice: 'We have recieved your request. Thanks for being patient.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /request_invites/1
  def update
    not_found
    if @request_invite.update(request_invite_params)
      redirect_to @request_invite, notice: 'Request invite was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /request_invites/1
  def destroy
    @request_invite.destroy
    redirect_to request_invites_url, notice: 'Request invite was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_invite
      @request_invite = RequestInvite.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def request_invite_params
      params.require(:request_invite).permit(:name, :about, :author, :what_write, :email, :paid, :fb_link, :twitter_link)
    end
end

app/helpers/request_invites_helper.rb
module RequestInvitesHelper
end

app/views/request_invites/_form.html.erb
<%= form_for(@request_invite) do |f| %>
  <% if @request_invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request_invite.errors.count, "error") %> prohibited this request_invite from being saved:</h2>

      <ul>
      <% @request_invite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.check_box :author %>
  </div>
  <div class="field">
    <%= f.label :what_write %><br>
    <%= f.text_area :what_write %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/request_invites/index.html.erb
<h1>Listing request_invites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>About</th>
      <th>Author</th>
      <th>What write</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @request_invites.each do |request_invite| %>
      <tr>
        <td><%= request_invite.name %></td>
        <td><%= request_invite.about %></td>
        <td><%= request_invite.author %></td>
        <td><%= request_invite.what_write %></td>
        <td><%= link_to 'Show', request_invite %></td>
        <td><%= link_to 'Edit', edit_request_invite_path(request_invite) %></td>
        <td><%= link_to 'Destroy', request_invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request invite', new_request_invite_path %>

app/views/request_invites/new.html.erb
<%= content_for :head do  %>
<!-- Facebook Conversion Code for Sqooz Share and Win -->
<script type="text/javascript">
window.loaded_addthis = true
var fb_param = {};
fb_param.pixel_id = '6013395140350';
fb_param.value = '0.00';
fb_param.currency = 'INR';
(function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
})();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6013395140350&amp;value=0&amp;currency=INR" /></noscript>
<% end %>
<div class="container white-box margin-top-30">
  <div class="row">
    <% if params.has_key?(:win) %>
      <div class="col-xs-10 margin-top-20 table-bordered padding-20 light-gray text-center col-xs-offset-1">
        <h1>
          Love writing and sharing awesome stuff on internet? Why not monetize what you love?
        </h1>
        
        <p class="large-font">
          Sqooz brings you its first open contest where you get paid between Rs 100-500 for writing and sharing stories on internet. Start <b><i>sqoozing</i></b> in three simple steps.  
        </p>
        <ul class="list-unstyled">
          <li>
            <h3>1. Request an invitaion</h3>
            <p class="large-font">
              Check you email for an invitation within 24 hours. We work hard to send invitations asap.
            </p>
          </li>
          <li>
            <h3>2. Write awesome stuff</h3>
            <p class="large-font">Write something unique that people will love. The more people love your stories that more you get paid.</p>
          </li>
          <li>
            <h3>3. Share it with the world</h3>
            <p class="large-font">Share it on as many social networks as possible. Sharing attracts more readers and you get paid more.</p>
          </li>
        </ul>       
        
        <span class="help-block">For more information please email us at <%= mail_to "lets@sqooz.it", "lets@sqooz.it", :target => "_blank", :class => "blue-link" %></span>
      </div>
    <% end %>
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-xs-offset-3">
      
      <h2>Request an invite</h2>
      <% unless params.has_key?(:win) %>
      <p>At this time we are doing lot of improvements to the site and have paused sending new invitations. But you can still request an invite, if you are patient.</p>
      <% end %>
      <%= form_for(@request_invite) do |f| %>
        <% if @request_invite.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@request_invite.errors.count, "error") %> prohibited this request_invite from being saved:</h2>

            <ul>
            <% @request_invite.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <div class="form-group" >
            <%= f.label :name %>
            <%= f.text_field :name, :autofocus => true, :class => "form-control required", :placeholder => "Name" %>
          </div>

          <div class="form-group" >
            <%= f.label :email, "Email" %>
            <%= f.text_field :email, :class => "form-control email required", :placeholder => "Email" %>
          </div>

          <div class="form-group" >
            <%= f.label :about, "Tell us something about you" %>
            <%= f.text_area :about, :class => "form-control required", :placeholder => "Tell us something about you" %>
          </div>
          <% if params.has_key?(:win) %>
            <%= f.hidden_field :paid, :value => true %>
            <div class="form-group" >
              <%= f.label :fb_link, "Facebook profile url" %>
              <%= f.text_field :fb_link, :class => "form-control required", :placeholder => "Facebook profile url" %>
            </div>
            <div class="form-group" >
              <%= f.label :twitter_link, "Twitter profile url" %>
              <%= f.text_field :twitter_link, :class => "form-control required", :placeholder => "Twitter profile url" %>
            </div>
          <% end %>
          <% if params.has_key?(:auth) %>
          
            
            <%= f.hidden_field :author, :value => true %>
          

          <div class="form-group" >
            <%= f.label :what_write, "What would you write about?" %>
            <%= f.text_area :what_write, :class => "form-control required", :placeholder => "What would you write about?" %>
          </div>
          <% end %>
          
          <div class="form-group">
            <%= f.submit "Request Invite", :class => "btn btn-primary" %>
            <span class="text-muted"> <!-- or </span> <%= link_to "Sign in", new_session_path(:user), :title => "Login" %>
            <%= link_to "Forgot your password?", new_password_path(:user), :class => "pull-right" %> -->
          </div>
      <% end %>
      <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
        <% ["facebook", "twitter", "stumbleupon", "pinterest_share", "email", "reddit", "blogger", "tumblr", "wordpress", "scoopit", "digg", "delicious"].each do |name| %>
          <a class="addthis_button_<%= name %>"></a>
        <% end %>
        <a class="addthis_counter addthis_bubble_style"></a>
        </div>
        <div class="margin-bottom-30"></div>
        <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
          <a class="addthis_button_google_plusone"></a>
          <a class="addthis_button_facebook_like"></a>
        </div>
        <!-- AddThis Button END -->
    </div>
     
          
  </div>
</div> 