config/routes.rb
Sqooz::Application.routes.draw do

  

  
  resources :request_invites, :only => [:new, :create]

  get "paid/sqoozers" => "static#paid_sqoozers", :as => :paid_sqoozer
  match "samples/email" => "static#send_sample_email", :as => :send_sample_email, via: [:get, :post]
  post "suggest_interest" => "interests#suggest", :as => :suggest_interest
  get "recommended(/:page)" => "feed#recommended", :as => :feed, constraints: { page: /\d+/ }

  get "search/(:page)" => "pages#search", :as => :search

  get "feed/activity(/:page)" => "feed#activity", :as => :feed_activity, constraints: { page: /\d+/ }
  get "trending(/:page)" => "feed#trending", :as => :feed_trending, constraints: { page: /\d+/ }
  get "feed/lists(/:page)" => "feed#lists", :as => :feed_list, constraints: { page: /\d+/ }
  get "feed/channels(/:page)" => "feed#channels", :as => :feed_channels, constraints: { page: /\d+/ }
  get "social/page/:id" => "pages#share_page", :as => :share_page
  devise_for :users

  resources :interests, :only => [:create, :destroy, :index]
  get "interest/:id/(/:page)"  => "interests#show", :as => :show_interest, constraints: { page: /\d+/ }
  get "tag/:name/(/:page)"  => "tags#show", :as => :show_tag, constraints: { page: /\d+/ }
  get "tags/(/:page)"  => "tags#index", :as => :tags, constraints: { page: /\d+/ }
  get "top/sqoozers(/:page)" => "discover#top_users", :as => :top_users, constraints: { page: /\d+/ }
  get "top/channels(/:page)" => "discover#top_channels", :as => :top_channels, constraints: { page: /\d+/ }
  resources :users do
    member do
      get "following/lists(/:page)"  => "users#following_lists", :as => :following_lists, constraints: { page: /\d+/ }
      get "following/channels(/:page)"  => "users#following_channels", :as => :following_channels, constraints: { page: /\d+/ }
      get "following(/:page)"  => "users#following", :as => :following, constraints: { page: /\d+/ }
     
      get "followers(/:page)"  => "users#followers", :as => :followers, constraints: { page: /\d+/ }
      get "interests(/:page)"  => "users#interests", :as => :interests, constraints: { page: /\d+/ }
      get "history(/:page)"  => "users#history", :as => :history, constraints: { page: /\d+/ }
      get "lists(/:page)"  => "users#lists", :as => :lists, constraints: { page: /\d+/ }
      get "comments(/:page)"  => "users#comments", :as => :comments, constraints: { page: /\d+/ }
      get "channels(/:page)"  => "users#channels", :as => :channels, constraints: { page: /\d+/ }
      get "notifications(/:page)"  => "users#notifications", :as => :notifications, constraints: { page: /\d+/ }
      get "likes(/:page)"  => "users#likes", :as => :likes,  constraints: {page: /\d+/}
      get "likes/filter/:filter(/:page)" => "users#likes", :as => :likes_ptype, constraints: { page: /\d+/ }
      get "likes/interest/:iname(/:page)" => "users#likes", :as => :likes_interest, constraints: { page: /\d+/ }
       get "likes/channel/:cname(/:page)" => "users#likes", :as => :likes_channel, constraints: { page: /\d+/ }
      get "pages(/:page)"  => "users#pages", :as => :pages,  constraints: {page: /\d+/}
      get "pages/list/:filter(/:page)" => "users#pages", :as => :pages_ptype, constraints: { page: /\d+/ }
      get "pages/interest/:iname(/:page)" => "users#pages", :as => :pages_interest, constraints: { page: /\d+/ }
      get "pages/channel/:cname(/:page)" => "users#pages", :as => :pages_channel, constraints: { page: /\d+/ }
    end

    collection do
      post "report_page" => "users#report", :as => :report
    end
  end

  post "follow" => "users#follow", :as => :follow

  resources :channels, :only => [:new, :edit,:create, :index, :show]
  resources :listings, :only => [:create, :destroy, :index]
  resources :comments, :only => [:create, :destroy, :index]
  resources :lists, :only => [:create, :destroy, :index]
  resources :likes, :only => [:create, :destroy]
  resources :pages, :only => [:create, :new, :edit, :update, :destroy] do
    member do
      get "about"
      post "about"
    end
    collection do
      post "photo/upload" => "pages#medium_photo_upload"
      post "photo/delete" => "pages#medium_photo_delete"
    end
  end

  post "pages/sqooz" => "pages#sqoozme", :as => :sqoozit
  get "sqoozing" => "pages#sqoozme", :as => :sqoozit_ad
  get "video/:sitename/:id" => "pages#show", :as => :video_show, :constraints => { :sitename => /[^\/]*/, :id => /[^\/]*/ }
  get "page/:id" => "pages#show", :as => :page_show, :constraints => { :sitename => /[^\/]*/, :id => /[^\/]*/ }
  get "about" => "static#about"
  get "help" => "static#help"
  get "discover/interests(/:page)" => "discover#interests", :as => :discover_interests
  get "discover/channels(/:page)" => "discover#channels", :as => :discover_channels

  root :to => 'static#welcome'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :find_user, :except => [:report, :follow]
  before_filter :notifications_count, :except =>  ["follow", "report"]
  before_filter :authenticate_user!, :only => [:follow, :notifications]
  before_filter :recently_viewed, :only => [:pages, :likes, :following, :following_lists,:following_channels, :followers, :lists, :comments]

  # def pages  THIS IS OLD VERSION OD PAGE WHEN WE HAD LISTS. We may have to bring it back
  #   @interests = @user.all_listing_interests
  #   @lists = @user.lists.order("title")
  #   @listings = @user.filtered_pages(params)
  #   @list = List.friendly.find(params[:filter]) if params[:filter]
  #   @interest = Interest.friendly.find(params[:iname]) if params[:iname]
  #   pagination_gon_variable(@listings.total_pages)
  #   respond_to do |format|
  #     format.html {render "pages.html.erb"}
  #     format.js { render "pages_xhr.html.erb", :layout => false, :status => 200 }
  #   end
  # end

  def pages
    @interests = Interest.where(:id => @user.pages.select("distinct interest_id"))
    @channels = Channel.where(:id => @user.pages.select("distinct channel_id"))
    @channel = Channel.friendly.find(params[:cname]) if params[:cname]
    @interest = Interest.friendly.find(params[:iname]) if params[:iname]
    @ptype = Page::PTYPES[params[:ptype]] if params[:ptype]
    if @interest
      @pages = @user.pages.where(:interest_id => @interest.id).page(params[:page] || 1).order("paged_at desc");
    elsif @channel
      @pages = @user.pages.where(:channel_id => @channel.id).page(params[:page] || 1).order("paged_at desc");
    elsif @ptype
      @pages = @user.pages.where(:ptype => @ptype).page(params[:page] || 1).order("paged_at desc");
    else
      @pages = @user.pages.page(params[:page] || 1).order("paged_at desc");
    end
  end

  def likes
    # TODO check if more indexes can be used here
    @interests = @user.all_likes_interests
    @channels = @user.all_likes_channels
    @likes = @user.filtered_likes(params)
    pagination_gon_variable(@likes.total_pages) if @likes.present?
    @interest = Interest.friendly.find(params[:iname]) if params[:iname]
    @channel = Channel.friendly.find(params[:cname]) if params[:cname]
    respond_to do |format|
      format.html {render "likes.html.erb"}
      format.js { render "likes_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def follow
    resource = params[:resource_type].constantize.find(params[:resource_id])
    if(params[:follow] == "1")
      current_user.follow(resource)
    elsif(params[:follow] == "0")
      current_user.stop_following(resource)
    end
    respond_to do |format|
      format.html {render :text => "", :status => 201}
      format.json { render :json => {:message => "ok"}, :status => 201 }
    end
  end

  def following
    @users = @user.following_by_type("User").order("follows.created_at desc").page(params[:page] || 1)
    pagination_gon_variable(@users.total_pages)
    respond_to do |format|
      format.html {render "following.html.erb"}
      format.js { render "following_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def following_lists
    @lists = @user.following_by_type("List").order("follows.created_at desc").includes(:user).page(params[:page] || 1)
    pagination_gon_variable(@lists.total_pages)
    respond_to do |format|
      format.html {render "following_lists.html.erb"}
      format.js { render "following_lists_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def following_channels
    @channels = @user.following_by_type("Channel").order("follows.created_at desc").page(params[:page] || 1).includes(:user)
    pagination_gon_variable(@channels.total_pages)
    respond_to do |format|
      format.html {render "following_channels.html.erb"}
      format.js { render "following_channels_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def followers
    @users = @user.user_followers.page(params[:page] || 1)
    @following_ids = Follow.select("followable_id").where(:follower_id => @user.id, :follower_type => "User", :blocked => false, :followable_type => 'User' ).map(&:followable_id) if @users.present?
    pagination_gon_variable(@users.total_pages)
    respond_to do |format|
      format.html {render "followers.html.erb"}
      format.js { render "followers_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def interests
    @interests = @user.interests.page(params[:page] || 1)
    pagination_gon_variable(@interests.total_pages)
    respond_to do |format|
      format.html {render "interests.html.erb"}
      format.js { render "interests_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def history
    @interests = @user.interests.select("name")
    @pageviews = @user.page_views.order("viewed_at desc").page(params[:page] || 1).includes(:page)
    pagination_gon_variable(@pageviews.total_pages)
    respond_to do |format|
      format.html {render "history.html.erb"}
      format.js { render "history_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def lists
    @lists = @user.lists.page(params[:page] || 1).order("updated_at desc")
    pagination_gon_variable(@lists.total_pages)
    respond_to do |format|
      format.html {render "lists.html.erb"}
      format.js { render "lists_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def notifications
    @following_ids = Follow.select("followable_id").where(:follower_id => @user.id, :follower_type => "User", :blocked => false, :followable_type => 'User' ).map(&:followable_id)
    @notifications = @user.notifications.latest.includes(:page, :actor).page(params[:page] || 1).per(40)
    pagination_gon_variable(@notifications.total_pages)
    @notifications.update_all(:viewed => true) # Run this in background
    respond_to do |format|
      format.html {render "notifications.html.erb"}
      format.js { render "notifications_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def comments
    @comments = @user.comments.page(params[:page] || 1).order("created_at desc").includes(:page)
    pagination_gon_variable(@comments.total_pages)
    respond_to do |format|
      format.html {render "comments.html.erb"}
      format.js { render "comments_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def tags
    @tags = @user.pages.tag_counts_on(:tags)
  end


  def channels
    @channels = @user.channels.page(params[:page] || 1).includes(:user)
    @following_ids = Follow.select("followable_id").where(:follower_id => @user.id, :follower_type => "User", :blocked => false, :followable_type => 'Channel' ).map(&:followable_id) if current_user != @user
    pagination_gon_variable(@channels.total_pages)
    respond_to do |format|
      format.html {render "channels.html.erb"}
      format.js { render "channels_xhr.html.erb", :layout => false, :status => 200 }
    end
  end

  def show
    redirect_to likes_user_path(@user), :status => :moved_permanently 
  end

  def report
    page = Page.friendly.find(params[:pageid])
    no_reverse = !params[:reverse]
    if page
      if params[:notme]
        no_reverse ? current_user.not_for_me(page) : current_user.yes_for_me(page)
      elsif params[:seenit]
        no_reverse ? current_user.seen_it_already(page) : current_user.unseen_it_already(page) 
      elsif params[:pagenoload]
        no_reverse ? current_user.report_page_no_load(page) : current_user.page_does_load(page)
      elsif params[:spam]
        no_reverse ? current_user.report_spam(page) : current_user.report_unspam(page)
      elsif params[:block]
        no_reverse ? current_user.block_this_page(page) : current_user.unblock_this_page(page)
      end
      next_page = current_user.sqoozit unless request.xhr?
      respond_to do |format|
        format.html { redirect_to next_page.slug_path, :notice => "Your request was updated.", :status => 200}
        format.json {render :json => {:message => "ok" }.to_json, :status => 200}
      end
    else
      respond_to do |format|
        format.html { not_found}
        format.json { render :json => {:error => "not_found"}, :status => 422 }
      end
    end
  end

private
  def find_user
    @user = User.friendly.find(params[:id])
    not_found unless @user
  end

  def recently_viewed
    @recently_viewed = @user.page_views.select("distinct page_id").limit(5).order("viewed_at desc").includes(:page)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  include ActsAsTaggableOn::TagsHelper



  def follow_unfollow_link(resource_type, resource_id, follow=true, cls=nil)
    if current_user
      if(follow)
        ("<div class='btn-group-vertical #{cls}'>" +  link_to("Follow", "javascript:void(0)" , :onclick => "follow('#{resource_type}', #{resource_id}, $(this))", :class => " follow btn  btn-primary ") +     link_to("Unfollow", "javascript:void(0)", :disabled => true, :onclick => "unfollow('#{resource_type}', #{resource_id}, $(this))", :class => "btn  btn-default unfollow ") +    '</div>').html_safe
      else
        ("<div class='btn-group-vertical #{cls}'>" +  link_to("Follow", "javascript:void(0)" , :onclick => "follow('#{resource_type}', #{resource_id}, $(this))", :disabled => true, :class => "follow btn btn-primary ") +     link_to("Unfollow", "javascript:void(0)", :onclick => "unfollow('#{resource_type}', #{resource_id}, $(this))", :class => "btn  btn-default unfollow ") +    '</div>').html_safe
      end
    else
      # ("<div class='btn-group-vertical #{cls}'>" +  link_to("Follow", "javascript:void(0)" , :onclick => "follow('#{resource_type}', #{resource_id}, $(this))", :class => "login btn  btn-primary ") +     link_to("Unfollow", "javascript:void(0)", :onclick => "unfollow('#{resource_type}', #{resource_id}, $(this))", :class => " login btn  btn-default unfollow ") +    '</div>').html_safe
      ("<div class='btn-group-vertical #{cls}'>" +  link_to("Follow", "javascript:void(0)" , :class => "login btn  btn-primary ") +     link_to("Unfollow", "javascript:void(0)", :class => " login btn  btn-default unfollow ") +    '</div>').html_safe
    end
  end

  def follow_unfollow_small_link(resource_type, resource_id, follow=true, cls=nil)
    if current_user
      if(follow)
        ( link_to("Follow", "javascript:void(0)" , :onclick => "follow('#{resource_type}', #{resource_id}, $(this))", :class => "follow jlink")).html_safe
      else
        (   link_to("Unfollow", "javascript:void(0)", :onclick => "unfollow('#{resource_type}', #{resource_id}, $(this))", :class => " unfollow jlink")).html_safe
      end
    else
      # ("<div class='btn-group-vertical #{cls}'>" +  link_to("Follow", "javascript:void(0)" , :onclick => "follow('#{resource_type}', #{resource_id}, $(this))", :class => "login btn  btn-primary ") +     link_to("Unfollow", "javascript:void(0)", :onclick => "unfollow('#{resource_type}', #{resource_id}, $(this))", :class => " login btn  btn-default unfollow ") +    '</div>').html_safe
      (link_to("Follow", "javascript:void(0)" , :class => "login") ).html_safe
    end
  end
end

app/views/users/_comment.html.erb
<li>
  <% page = comment.page %>
  <div class="media">
    <%= link_to (image_tag page.photo(:thumb), :class => "media-object comment-img img-thumbnail", :alt => page.title).html_safe, page.slug_path , :class => "pull-left"  %>

    <div class="media-body">
      <div class="clearfix">
        <h2 class="media-heading pull-left"><%= link_to page.title, page.slug_path %></h2>
      </div>
      <p class="about-record"><%= about_page_truncate(page) %></p>
      <div class="clearfix">
        <ul class="list-inline pull-left">
          <% if page.likes_count > 0 %>
          <li>
            <%= "#{page.likes_count} likes" %>
          </li>
          <% end %>
          <% if page.comments_count > 0 %>
            <li>
              <%= "#{page.comments_count} comments"  %>
            </li>
          <% end %>
          <% if page.saves_count > 0 %>
            <li>
              <%= "#{page.saves_count} added to list"  %>
            </li>
          <% end %>
        </ul>

        <ul class="list-inline pull-right">
          <li><%= link_to "<span class='glyphicon glyphicon-plus'></span>".html_safe, "javascript:void(0)", :class => "special-hover-link #{current_user ? 'add-to-list' : 'login'}", :data => {:page => page.slug, :id => page.id} %>
          </li>
          <li>
            <%= link_to "<span class='glyphicon glyphicon-comment'></span>".html_safe,  "javascript:void(0)", :class => "special-hover-link #{current_user ? 'comment-on-page' : 'login'}", :data => {:page => page.slug, :id => page.id, :interest_id => page.interest_id} %>
          </li>
          <li>
            <%= link_to "<span class='glyphicon glyphicon-share'></span>".html_safe, "javascript:void(0)" , :class => "special-hover-link #{current_user ? 'share-the-page' : 'login'}",  :data => {:url => page.slug_url, :title => page.title, :description => page.plain_about} %>
          </li>
          <li class="page-domain">
            <p><%= page.domain %></p>
          </li>
        </ul>
      </div>
      
    </div>
    <div class="comment-blk"><%= comment.content %></div>
  </div>

</li>

app/views/users/_likes_filter.html.erb
<div class="col-xs-12"> 
  <% if @interest %>
  <h1><%= @user.username.titleize %>'s <%= @interest.name %> Likes</h1>
  <% else %>
  <h1><%= @user.username.titleize %>'s Likes</h1>
  <% end %>
  <ul class="nav margin-0 nav-pills inner-filters text-left">
    <li class="<%= 'active' if !params[:filter] && !params[:iname] %>">
      <%= link_to "All", likes_user_path(@user) %>
    </li>
    <% if params[:iname] %>
    <li class="dropdown active">
         <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
          <%= @interests.all.find{|i| i.slug == params[:iname]}.try(:name) %> <span class="caret"></span>
        </a>
      <% else %>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
          By Interest <span class="caret"></span>
        </a>
      <% end %>
      <ul class="dropdown-menu" role="menu">
        <% @interests.each do |int| %>
          <li>
            <%= link_to int.name, likes_interest_user_path(@user, int.slug) %>
          </li>
        <% end %>
      </ul>
    </li>
    <% if params[:cname] %>
    <li class="dropdown active">
         <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
          <%= @channels.all.find{|i| i.slug == params[:cname]}.try(:title) %> <span class="caret"></span>
        </a>
      <% else %>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
          By Channel<span class="caret"></span>
        </a>
      <% end %>
      
      <ul class="dropdown-menu" role="menu">
        <% @channels.each do |channel| %>
          <li>
          <%# This is ptype_path coz we used to have many ptype but later we decided to use just videos, that is why we just used same old paths %>
            <%= link_to channel.title, likes_channel_user_path(@user, channel.slug) %>
          </li>
        <% end %>
      </ul>
    </li>
  </ul>
</div>

app/views/users/_user.html.erb
<% return if current_user.try(:id) == user.id %>
<li class="row my-border clearfix">
<div class="media col-xs-10">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-0 col-sm-4 col-sm-offset-0 col-md-3 col-lg-2 thumb-container">
      <%= link_to (image_tag user.avatar(:thumb), :class => "media-object user-thumb", :alt => user.username).html_safe, user_path(user) %>
    </div>
    <div  class="col-xs-6 col-sm-8 col-md-9 col-lg-8 media-body-container">
      <div class="media-body">
      <div class="clearfix">
        <h3 class="media-heading"><%= link_to user.username, user_path(user) %></h3>
      </div>
      <p class="about-record"><%= truncate(user.about, :length => 40, omission: '...') %> <%= link_to "view more", user_path(user), :class => "special-hover-link" %></p>
      <ul class="list-inline links-layer">
        <li>
          <!-- TODO: Fix it -->
          <%= link_to "#{user.likes_count} Likes", likes_user_path(user) %>
        </li>
        <li>
          <%= link_to "#{user.pages_count} Pages", pages_user_path(user) %>
        </li>
        <li>
          <!-- TODO: Fix it -->
          <%= link_to "#{user.lists_count} Lists", lists_user_path(user) %>
        </li>
        <li>
          <%= link_to "#{user.comments_count} Comments", comments_user_path(user) %>
        </li>
        <li>
          <%= link_to "#{user.follows_counter} Following", following_user_path(user) %>
        </li>
        <li>
          <%= link_to "#{user.followers_counter} Followers", followers_user_path(user) %>
        </li>
      </ul>
    </div>
    </div>
  </div>
</div>

<div class="padding-5 col-xs-2">
<% if  @following_ids %>
  <%= follow_unfollow_link("User", user.id, !@following_ids.include?(user.id), "pull-right") %>
<% else %>
  <%= follow_unfollow_link("User", user.id, !following, "pull-right") %>
<% end %>
</div>
</li>

app/views/users/channels_xhr.html.erb
<%= render partial: "channels/channel", collection: @channels %>

app/views/users/comments.html.erb
<% content_for :title, "#{@user.username} comments on #{SITENAME}" %>
<% content_for :description, "Most recent comment from #{@user.username}: #{@comments[0].try(:content)}"  %>
<div class="container" id="comments-container">
<div class="margin-top-30"></div>
    <div class="row">

      <div class="col-xs-12 col-sm-4 col-sm-push-8">

        <div class="page-container user-profile-container">
          <%= render :partial => "shared/user_info" %>
        </div>
      </div>
      
      <div class="col-xs-12 col-sm-8 col-sm-pull-4">
        <h1><%= @user.username.titleize %> Comments</h1>
        <div id="my-list-container">
          <ul class="list-unstyled">
            <%= render partial: "comment", collection: @comments %>
          </ul>
      </div>
    </div>


   <%= link_to_next_page @comments, 'Next Page', :class => "hide" %>

</div>

app/views/users/followers.html.erb
<% content_for :title, "#{@user.username} followers on #{SITENAME}" %>
<% content_for :description, "#{@user.username} is followed #{pluralize(@users.total_count, 'user')} on #{SITENAME}. Follow #{@user.username} on #{SITENAME}" %>
<div class="container" >
  <div class="margin-bottom-30"></div>
  <div class="row">
   


    <div class="col-xs-12 col-sm-4 col-sm-push-8">
      <div class="page-container user-profile-container">
        <%= render :partial => "shared/user_info" %>
      </div>
    </div>
    
    <div class="col-xs-12 col-sm-8 col-sm-pull-4">
      <%= @user.username.titleize %> Followers
      <div id="my-list-container">

        <ul class="list-unstyled">
          <%= render partial: "user", collection: @users %>
        </ul>
      </div>
    </div>

  </div>
  
  <%= link_to_next_page @users, 'Next Page', :class => "hide" %>

</div>

app/views/users/following_channels.html.erb
<div class="container" >
  <div class="row">
    <div class="col-xs-12">
      <h1>Channels followed by <%= @user.username %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div id="masnory-container-channel">
        <%= render partial: "channels/channel", collection: @channels %>
      </div>
    </div>
  </div>
</div>

app/views/users/following_xhr.html.erb
<%= render partial: "user", collection: @users, :locals => {:following => true} %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/lists.html.erb
<% content_for :title, "Lists created by #{@user.username} on #{SITENAME}" %>
<% content_for :description, "#{@user.username} has #{pluralize(@lists.total_count, 'list')} on #{SITENAME}. Check #{@lists[0..2].map{|l| l.title}.join(", ")} and more on #{SITENAME}"  %>
<%#= render :partial => "shared/user_info" %>

<div class="container" >
  <div class="margin-top-30"></div>
  <div class="row">
    

    <div class="col-xs-12 col-sm-4 col-sm-push-8">
      
      <div class="page-container user-profile-container">
        <%= render :partial => "shared/user_info" %>
      </div>
    </div>
    
    <div class="col-xs-12 col-sm-8 col-sm-pull-4">
    <h1><%= @user.username.titleize %> Lists</h1>
      <div id="my-list-container">
        <ul class="list-unstyled">
          <%= render partial: "list", collection: @lists %>
        </ul>
      </div>
    </div>
  </div>


  <%= link_to_next_page @lists, 'Next Page' %>

</div>

app/views/users/notifications.html.erb
<div class="container margin-top-30" id="notification-container" >
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h3>Your Notifications</h3>
      <div id="my-list-container">
        <table class="table table-hover">
          <%= render partial: "notification", collection: @notifications %>
        </table>
      </div>
    </div>
  </div>
  
  <%= link_to_next_page @notifications, 'Next Page', :class => "hide" %>

</div>

app/views/users/pages_xhr.html.erb
<%= render partial: "pages/page", collection: @listings, :as => :listing, :locals => {:channel => true} %>