config/routes.rb
Sqooz::Application.routes.draw do

  

  
  resources :request_invites, :only => [:new, :create]

  get "paid/sqoozers" => "static#paid_sqoozers", :as => :paid_sqoozer
  match "samples/email" => "static#send_sample_email", :as => :send_sample_email, via: [:get, :post]
  post "suggest_interest" => "interests#suggest", :as => :suggest_interest
  get "recommended(/:page)" => "feed#recommended", :as => :feed, constraints: { page: /\d+/ }

  get "search/(:page)" => "pages#search", :as => :search

  get "feed/activity(/:page)" => "feed#activity", :as => :feed_activity, constraints: { page: /\d+/ }
  get "trending(/:page)" => "feed#trending", :as => :feed_trending, constraints: { page: /\d+/ }
  get "feed/lists(/:page)" => "feed#lists", :as => :feed_list, constraints: { page: /\d+/ }
  get "feed/channels(/:page)" => "feed#channels", :as => :feed_channels, constraints: { page: /\d+/ }
  get "social/page/:id" => "pages#share_page", :as => :share_page
  devise_for :users

  resources :interests, :only => [:create, :destroy, :index]
  get "interest/:id/(/:page)"  => "interests#show", :as => :show_interest, constraints: { page: /\d+/ }
  get "tag/:name/(/:page)"  => "tags#show", :as => :show_tag, constraints: { page: /\d+/ }
  get "tags/(/:page)"  => "tags#index", :as => :tags, constraints: { page: /\d+/ }
  get "top/sqoozers(/:page)" => "discover#top_users", :as => :top_users, constraints: { page: /\d+/ }
  get "top/channels(/:page)" => "discover#top_channels", :as => :top_channels, constraints: { page: /\d+/ }
  resources :users do
    member do
      get "following/lists(/:page)"  => "users#following_lists", :as => :following_lists, constraints: { page: /\d+/ }
      get "following/channels(/:page)"  => "users#following_channels", :as => :following_channels, constraints: { page: /\d+/ }
      get "following(/:page)"  => "users#following", :as => :following, constraints: { page: /\d+/ }
     
      get "followers(/:page)"  => "users#followers", :as => :followers, constraints: { page: /\d+/ }
      get "interests(/:page)"  => "users#interests", :as => :interests, constraints: { page: /\d+/ }
      get "history(/:page)"  => "users#history", :as => :history, constraints: { page: /\d+/ }
      get "lists(/:page)"  => "users#lists", :as => :lists, constraints: { page: /\d+/ }
      get "comments(/:page)"  => "users#comments", :as => :comments, constraints: { page: /\d+/ }
      get "channels(/:page)"  => "users#channels", :as => :channels, constraints: { page: /\d+/ }
      get "notifications(/:page)"  => "users#notifications", :as => :notifications, constraints: { page: /\d+/ }
      get "likes(/:page)"  => "users#likes", :as => :likes,  constraints: {page: /\d+/}
      get "likes/filter/:filter(/:page)" => "users#likes", :as => :likes_ptype, constraints: { page: /\d+/ }
      get "likes/interest/:iname(/:page)" => "users#likes", :as => :likes_interest, constraints: { page: /\d+/ }
       get "likes/channel/:cname(/:page)" => "users#likes", :as => :likes_channel, constraints: { page: /\d+/ }
      get "pages(/:page)"  => "users#pages", :as => :pages,  constraints: {page: /\d+/}
      get "pages/list/:filter(/:page)" => "users#pages", :as => :pages_ptype, constraints: { page: /\d+/ }
      get "pages/interest/:iname(/:page)" => "users#pages", :as => :pages_interest, constraints: { page: /\d+/ }
      get "pages/channel/:cname(/:page)" => "users#pages", :as => :pages_channel, constraints: { page: /\d+/ }
    end

    collection do
      post "report_page" => "users#report", :as => :report
    end
  end

  post "follow" => "users#follow", :as => :follow

  resources :channels, :only => [:new, :edit,:create, :index, :show]
  resources :listings, :only => [:create, :destroy, :index]
  resources :comments, :only => [:create, :destroy, :index]
  resources :lists, :only => [:create, :destroy, :index]
  resources :likes, :only => [:create, :destroy]
  resources :pages, :only => [:create, :new, :edit, :update, :destroy] do
    member do
      get "about"
      post "about"
    end
    collection do
      post "photo/upload" => "pages#medium_photo_upload"
      post "photo/delete" => "pages#medium_photo_delete"
    end
  end

  post "pages/sqooz" => "pages#sqoozme", :as => :sqoozit
  get "sqoozing" => "pages#sqoozme", :as => :sqoozit_ad
  get "video/:sitename/:id" => "pages#show", :as => :video_show, :constraints => { :sitename => /[^\/]*/, :id => /[^\/]*/ }
  get "page/:id" => "pages#show", :as => :page_show, :constraints => { :sitename => /[^\/]*/, :id => /[^\/]*/ }
  get "about" => "static#about"
  get "help" => "static#help"
  get "discover/interests(/:page)" => "discover#interests", :as => :discover_interests
  get "discover/channels(/:page)" => "discover#channels", :as => :discover_channels

  root :to => 'static#welcome'

end

app/views/shared/_best_video_modal.html.erb
<div role="dialog" aria-labelledby="Video" aria-hidden="true" id="best_video_modal">
  <p id="close_best_video_modal">
    Click anywhere to go back...
  </p>
  <h2 id="best-title">The Best of Sqooz</h2>
  <div id="best-masnory-container">
    <% @best_pages.each do |bp| %>
      <div class="best-page">
        <%= link_to image_tag(bp.photo(:medium)), bp.slug_path, :alt => bp.title, :title => bp.title %>
        <hr />
        <h2 class="normal-font">
          <%= link_to bp.title, bp.slug_path, :title => bp.title %>
        </h2>
        <hr />
      </div>
    <% end %>
  </div> 
</div><!-- /.modal -->

app/views/shared/_comment_modal.html.erb
<div role="dialog" aria-labelledby="Comments" aria-hidden="true" id="page_comments" class="my-modal modal slide">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <% if @comments.present? %>
          <h3 class="modal-title text-left margin-bottom-10">Comments</h3>
          <div id="table-scroll">
            <ul class="media-list">
              <% @comments.each do |com| %>
                <li class="media" id="comment<%= com.id %>">
                  <%= link_to image_tag(com.user.avatar(:thumb), :class => "sthumbnail").html_safe, user_path(com.user), :class => "pull-left", :alt => com.user.username, :title => com.user.username %>
                  <div class="media-body">
                    <p class="media-heading margin-0 small help-block">Commented By <strong><em><%= com.user.username %></em></strong></p>
                    <%= com.content %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        <% else %>
          <h3 class="margin-0">Be the first to comment on this page.</h3>
        <% end %>
      </div>
      <div class="modal-body">
        <%= form_for Comment.new, :role => "form", :remote => true do |f| %>
        <!-- <form class="form-inline" role="search">  -->
          <%= f.hidden_field :page_id, :value => @page.id %>
          <div class="form-group">
            <%= f.text_area :content, :class => "form-control", :placeholder => "Write you comment" %>
          </div>
          <%= f.submit "Comment",:data =>{ :disable_with => "Please wait..." }, :class => "btn btn-primary"  %>
        <% end %>
      </div>
      <div class="modal-footer margin-top-0">
        <%= link_to "Close", "", :"data-dismiss" => "modal", :title => "Clode" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_header.html.erb
<% if current_user %>
<header>
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation"  >
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container-fluid margin-0">

      <ul class="nav navbar-nav pull-left margin-0 horiz-navbar">
        <li class="first">
          <a class="margin-right-0" id="sidebar-toggle", title ="Menu" >
            <span class="glyphicon glyphicon-th-list"></span>
          </a> 
        </li>
        <% if @pending_notification_count && @pending_notification_count > 0 %>
          <li class="hidden-xs">
            <%= link_to("<span class='badge'>#{@pending_notification_count}</span>".html_safe, notifications_user_path(current_user), :title => "Notifications" )  %>
          </li>
        <% end %>
       
        <li class="hidden-xs" id="home-nav">
          <%= link_to '<span class="glyphicon glyphicon-home"></span>'.html_safe ,root_path, :class => "darker-nav", :title => "Home"  %>
        </li>

        <li>
          <%= link_to '<span class="glyphicon glyphicon glyphicon-tower"></span>'.html_safe, feed_trending_path, :class => "darker-nav" , :title => "Trending Pages"  %>
        </li>
       
        <li>
          <%= link_to '<span class="glyphicon glyphicon-list-alt"></span>'.html_safe, top_channels_path,  :class => "darker-nav",  :title => "Top Channels" %>
        </li>

        <li class="dropdown <%= 'active' if cookies[:current_interest_id].present? %>" id="interest-links">
          <%= link_to  "#{cookies[:current_interest_name].present?  ? cookies[:current_interest_name]  : 'All Interests' } <span class='caret'></span>".html_safe ,"javascript:void(0)", :class => "dropdown-toggle darker-nav", :"data-toggle" => "dropdown", :title => "Block Page" %>
          <ul class="dropdown-menu">
            <% @all_interests.each do |int| %>
              <li><%= link_to int.name, "javascript:void(0);" , :data => {:id => int.id}%></li>
            <% end %>
          </ul>
        </li>
          

        
      </ul>
      
      <ul id="sqoozer-head" class="nav navbar-nav navbar-left margin-0">
        <div id="sqooz-prompt" ></div>
        <li class="first">
          <%= form_tag sqoozit_path , id: "sqooz-from" do %>
            <%= hidden_field_tag "int", cookies[:current_interest_id] %>
            <%= button_to "Sqooz".html_safe, sqoozit_path, :class => "btn btn-success", :id => "sqooz-button", :type => "post", :onclick => "return false;" %>
          <% end %>
            
        </li>
      </ul>
      
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <% if params[:action] == "show" && params[:controller] == "pages" %>
        
        <div class="collapse navbar-collapse" id="top-navigation">

          <ul class="nav navbar-nav navbar-right margin-0">
            <li>
              <%= form_tag search_path, :class => "navbar-form navbar-right", :role => "search", :id =>"search_form", :method => "get" do %>
              
                <div class="form-group left-inner-addon">
                  <i class="glyphicon glyphicon-search hidden-xs"></i> <input type="text" name="q" class="form-control" placeholder="Search">
                  <%= hidden_field_tag "int",  cookies[:current_interest_id] %>
                </div>
              <% end %>
            </li>
            <li class="first">
              <%= link_to '<span class="glyphicon glyphicon-thumbs-down"></span>'.html_safe ,root_path, :class => "darker-nav #{'yellow' if @liked ==  false}" , :id => "unlike-page", :title => "Unlike"  %>       
            </li>
          
           <!--  <li class="dropdown" id="report-links">
              <%#= link_to "<span class='glyphicon glyphicon-list-alt'></span>".html_safe ,"javascript:void(0)", :class => "dropdown-toggle darker-nav", :"data-toggle" => "dropdown", :title => "Block Page" %>
               <ul class="dropdown-menu">
                <li><%#= link_to_blockers "Not for me", report_users_path(:pageid => @page.slug, :notme => true), "not_for_me", @page %></li>
                <li><%#= link_to_blockers "Seen Page Already", report_users_path(:pageid => @page.slug, :seenit => true), "seent_it", @page  %></li>
                <li><%#= link_to_blockers "Page Does Not Load", report_users_path( :pageid => @page.slug, :pagenoload => true), "noloading", @page %></li>
                <li><%#= link_to_blockers "Report as Spam", report_users_path(:pageid => @page.slug, :spam => true), "spam_ids", @page %></li>
                <li class="divider"></li>
                <li><%#= link_to_blockers "Block #{@page.domain}", report_users_path(:pageid => @page.slug, :block => true), "domain_ids", @page %></li>
              </ul>
            </li>
           -->
            <li>
              <%= link_to '<span class="glyphicon glyphicon-thumbs-up"></span>'.html_safe ,root_path, :class => "darker-nav #{'yellow' if @liked ==  true}" , :id => "like-page", :title => "Like" %>
            </li>
            <!-- <li id="add-icon">
              <%#= link_to '<span class="glyphicon glyphicon-plus"></span>'.html_safe ,root_path, :class => "darker-nav add-to-list", :data => {:page => @page.slug, :id => @page.id, :interest_id => @page.interest_id}, :title => "Add to list" %>
            </li> -->
            <li id="comment-icon">
              <%= link_to '<span class="glyphicon glyphicon-comment"></span>'.html_safe.html_safe ,root_path, :class => "darker-nav comment-on-page", :data => {:page => @page.slug, :id => @page.id}, :title => "Comment" %>
            </li>
            <li id="share-icon">
              <%= link_to '<span class="glyphicon glyphicon-share"></span>'.html_safe.html_safe ,root_path, :class => "darker-nav share-the-page",  :data => {:url => @page.slug_url, :title => @page.title, :description => @page.plain_about}, :title => "Share" %>
            </li>
                       
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="top-navigation">
          <%= form_tag search_path, :method => :get, :class => "navbar-form navbar-right", :role => "search", :id => "search_form" do %>
            <div class="form-group left-inner-addon">
              <i class="glyphicon glyphicon-search"></i> <input type="text" name="q" class="form-control" value="<%= params[:q] %>" placeholder="Search">
              <%= hidden_field_tag "int", cookies[:current_interest_id] %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= get_navbar_sprinkle %>
  </nav>
  
</header>
<% else  %>
<header>
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation"  >
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container-fluid margin-0">

      <ul class="nav navbar-nav pull-left margin-0 horiz-navbar">
        <li class="first">
          <a class="margin-right-0" id="sidebar-toggle" title = "Menu" >
            <span class="glyphicon glyphicon-th-list"></span>
            
          </a> 
        </li>
       
        <li class="hidden-xs" id="home-nav" >
          <%= link_to '<span class="glyphicon glyphicon-home"></span>'.html_safe ,root_path, :class => "darker-nav", :title => "Home"  %>
        </li>
        <li>
          <%= link_to '<span class="glyphicon glyphicon glyphicon-tower"></span>'.html_safe, feed_trending_path, :class => "darker-nav" , :title => "Trending Pages"  %>
        </li>
       
        <li>
          <%= link_to '<span class="glyphicon glyphicon-list-alt"></span>'.html_safe, top_channels_path,  :class => "darker-nav",  :title => "Top Channels" %>
        </li>

        <li class="dropdown <%= 'active' if cookies[:current_interest_id].present? %>" id="interest-links">
          <%= link_to  "#{cookies[:current_interest_name].present?  ? cookies[:current_interest_name]  : 'All Interests' } <span class='caret'></span>".html_safe ,"javascript:void(0)", :class => "dropdown-toggle darker-nav", :"data-toggle" => "dropdown", :title => "Block Page" %>
          <ul class="dropdown-menu">
            <% @all_interests.each do |int| %>
              <li><%= link_to int.name, "javascript:void(0);" , :data => {:id => int.id}%></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul id="sqoozer-head" class="nav navbar-nav navbar-left margin-0">
        
        <li class="first">
          <%= form_tag sqoozit_path, :id => "sqooz-from" do %>
            <%= hidden_field_tag "int", cookies[:current_interest_id] %>
            <%= button_to "Sqooz".html_safe, sqoozit_path, :id => "sqooz-button", :class => "btn btn-success", :type => "post", :onclick => "return false;" %>
          <% end %>
            
        </li>
      </ul>
      

      <% if params[:action] == "show" && params[:controller] == "pages" %>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="top-navigation">
          <ul class="nav navbar-nav navbar-right margin-0">
            <li>
              <%= form_tag search_path, :class => "navbar-form navbar-right", :role => "search", :id =>"search_form", :method => "get" do %>
              
                <div class="form-group left-inner-addon">
                  <i class="glyphicon glyphicon-search"></i> <input type="text" name="q" class="form-control" placeholder="Search">
                  <%= hidden_field_tag "int",  cookies[:current_interest_id] %>
                </div>
              <% end %>
            </li>
            <li class="first">
              <%= link_to '<span class="glyphicon glyphicon-thumbs-down"></span>'.html_safe ,root_path, :class => "login darker-nav #{'yellow' if @liked ==  false}", :title => "Unlike"  %>       
            </li>
          
            <li>
              <%= link_to '<span class="glyphicon glyphicon-thumbs-up"></span>'.html_safe ,root_path, :class => "login darker-nav #{'yellow' if @liked ==  true}", :title => "Like" %>
            </li>
            <li id="add-icon">
              <%= link_to '<span class="glyphicon glyphicon-plus"></span>'.html_safe ,root_path, :class => "darker-nav login", :data => {:page => @page.slug, :id => @page.id, :interest_id => @page.interest_id}, :title => "Add to list" %>
            </li>
            <li id="comment-icon">
              <%= link_to '<span class="glyphicon glyphicon-comment"></span>'.html_safe.html_safe ,root_path, :class => "darker-nav login", :data => {:page => @page.slug, :id => @page.id}, :title => "Comment" %>
            </li>
            <li id="share-icon">
              <%= link_to '<span class="glyphicon glyphicon-share"></span>'.html_safe.html_safe ,root_path, :class => "darker-nav login", :title => "Share", :data => {:url => @page.slug_url, :title => @page.title, :description => @page.plain_about} %>
            </li>
                       
          </ul>
        </div>
      <% else %>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="top-navigation">
          <ul class="nav navbar-nav pull-right margin-0">
            <li>
              <%= form_tag search_path, :class => "navbar-form navbar-right", :role => "search", :id =>"search_form", :method => "get" do %>
              
                <div class="form-group left-inner-addon">
                  <i class="glyphicon glyphicon-search hidden-xs"></i> <input type="text" name="q" class="form-control" placeholder="Search">
                  <%= hidden_field_tag "int",  cookies[:current_interest_id] %>
                </div>
              <% end %>
            </li>
            <li class="first">
              <%= link_to '<span class="glyphicon glyphicon-log-in"></span>'.html_safe ,root_path , :class => "darker-nav login", :title => "Login" %>       
            </li>
          </ul>
        </div>
      <% end %>
    </div>
    <%= get_navbar_sprinkle %>
  </nav>
  
</header>
<% end %>

app/views/shared/_sidebar.html.erb
<% if current_user %>
<div id="sidebar" aria-labelledby="Sidebar" aria-hidden="true" class="affix <%= 'shownow' if cookies[:sidebar_hidden] == 'false' %> " >
  <div id="sidebar-head">
    <h4 class="text-center margin-0">Navigation</h4>
  </div>
  <div class="list-group">
    <a href="javascript:void(0)" data-toggle="collapse" data-target="#current-user-items" class="list-group-item heading">
      <span class="glyphicon glyphicon-user"></span><%= current_user.username %>
      <span class="caret right"></span>
    </a>
    <div class="collapse list-group-items" id="current-user-items">
      <%= link_to_active "Your Favorites", likes_user_path(current_user) , :class => "list-group-item"%>
      <%= link_to_active "Following", following_channels_user_path(current_user) , :class => "list-group-item"%>
      
      <% if current_user.try(:author) %>
        <%= link_to_active "Your Channels", channels_user_path(current_user) , :class => "list-group-item"%>
        <%= link_to_active "Add a Channel", new_channel_path , :class => "list-group-item"%>
        <%= link_to_active "Your Pages", pages_user_path(current_user) , :class => "list-group-item"%>
        <%= link_to_active "Add a Video", new_page_path(:ptype => Page::PTYPES["video"]) , :class => "list-group-item"%>
        <%= link_to_active "Write a Story", new_page_path(:ptype => Page::PTYPES["story"]) , :class => "list-group-item"%>
      <% end %>
      <%#= link_to_active "Your Comments", comments_user_path(current_user) , :class => "list-group-item"%>
      <%#= link_to_active "History", history_user_path(current_user) , :class => "list-group-item"%>
      <%#= link_to_active "Interests", interests_user_path(current_user) , :class => "list-group-item"%>
      <%# Lets do tags later %>
      <%#= link_to_active "Tags", tags_user_path(current_user) , :class => "list-group-item"%>
      <%= link_to_active "Paid Sqoozer", paid_sqoozer_path, :class => "list-group-item" if current_user.paid %>
      <%= link_to_active "Log Out", destroy_session_path(:user) , :class => "list-group-item", :method => "delete" %>
    </div>
  </div>
  <div class="list-group">
    <a href="javascript:void(0)" data-toggle="collapse" data-target="#explore-items" class="list-group-item heading">
      <span class="glyphicon glyphicon-eye-open"></span>Explore
      <span class="caret right"></span>
    </a>
    <div class="collapse list-group-items" id="explore-items">
      
      <%= link_to_active "Interests", interests_path, :class => "list-group-item" %>

     <!--  <a href="<%#= tags_path %>"  class="list-group-item">
      Tags
      </a> -->
      <%= link_to_active "Top Channels", top_channels_path, :class => "list-group-item" %>
      
      <%= link_to_active "Recommended", feed_path , :class => "list-group-item"%>
      <%= link_to_active "Trending", feed_trending_path , :class => "list-group-item"%>
    </div>
  </div>
  <div class="list-group">
    <a href="javascript:void(0)" data-toggle="collapse" data-target="#home-items" class="list-group-item heading">
      <span class="glyphicon glyphicon-tasks"></span>Feed
      <span class="caret  right"></span>
    </a>
    <div class="collapse list-group-items" id="home-items">
      
      <%= link_to_active "Activity", feed_activity_path , :class => "list-group-item"%>
      
    </div>
  </div>
  <div class="list-group">
    <a href="javascript:void(0)" data-toggle="collapse" data-target="#follow-items" class="list-group-item heading">
      <span class="glyphicon glyphicon-random"></span>Follow
      <span class="caret right"></span>
    </a>
    
    <div class="collapse list-group-items" id="follow-items">
      <%= link_to_active "Interests", discover_interests_path , :class => "list-group-item"%>
      <%= link_to_active "Channels", discover_channels_path , :class => "list-group-item"%>
    </div>
  </div>
  <% if current_user.try(:author) %>
    <div class="list-group">
      <% if @pending_notification_count && @pending_notification_count > 0 %>
        <%= link_to_active "<span class='glyphicon glyphicon-bullhorn'></span> Notifications<span class='badge'>#{@pending_notification_count}</span>".html_safe, notifications_user_path(current_user) , :class => "list-group-item" %>
      <% else %>
        <%= link_to_active "<span class='glyphicon glyphicon-bullhorn'></span>Notifications".html_safe, notifications_user_path(current_user) , :class => "list-group-item" %>
      <% end %>
    </div>
  <% end %>
  <div class="list-group">
    <%= mail_to "lets@sqooz.it", "<span class='glyphicon glyphicon-warning-sign'></span>Report an issue".html_safe , :class => "list-group-item", :target => "_blank" %>
  </div>
</div>
<% else %>
<div id="sidebar" class="affix <%= 'shownow' if cookies[:sidebar_hidden] == 'false' %> " >
  <div id="sidebar-head">
    <h4 class="text-center margin-0">Navigation</h4>
  </div>
  <div class="list-group">
    <a href="javascript:void(0)" data-toggle="collapse" data-target="#home-items" class="list-group-item login heading">
      <span class="glyphicon glyphicon-log-in"></span>Login 
      
    </a>
  </div>
  <div class="list-group">
    <a href="javascript:void(0)" data-toggle="collapse" data-target="#explore-items" class="list-group-item heading">
      <span class="glyphicon glyphicon-eye-open"></span>Explore
      <span class="caret right"></span>
    </a>
    <div class="collapse list-group-items" id="explore-items">
      <%= link_to_active "Interests", interests_path, :class => "list-group-item" %>
      <%= link_to_active "Top Channels", top_channels_path, :class => "list-group-item" %>
      <%= link_to_active "Trending", feed_trending_path , :class => "list-group-item"%>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_user_info.html.erb
<div id="user-info">
    <ul id="detail-block" class="list-unstyled  text-center">
      <li>
        <%= link_to image_tag(@user.avatar(:thumb), :class => "img-circle").html_safe, user_path(@user), :alt => @user.username %>
      </li>
      <li>
        <h2 class="margin-0 margin-bottom-10">
          <%= link_to @user.username , user_path(@user), :class => "special-hover-link" %>
        </h2>
      </li>
      <% if @user.about.present? %>
        <li>
          <h3 class="normal-font margin-bottom-10"><%= @user.about %></h3>
        </li>
      <% end %>
    </ul>

    <ul class="nav nav-pills" id="user-statistics">
      <li>
        <%= link_to "#{@user.likes_count} <p class='margin-0'>Likes</p>".html_safe, likes_user_path(@user) %>
      </li>
      <li>
        <%= link_to "#{@user.pages_count} <p class='margin-0'>Pages</p>".html_safe, pages_user_path(@user) %>
      </li>
    
      <li>
        <%= link_to "#{@user.comments_count} <p class='margin-0'>Comments</p>".html_safe, comments_user_path(@user) %>
      </li>
      <li>
        <%= link_to "#{@user.follows_counter} <p class='margin-0'>Following</p>".html_safe, following_user_path(@user) %>
      </li>
      <li class="last">
        <%= link_to "#{@user.channels_count} <p class='margin-0'>Channels</p>".html_safe, channels_user_path(@user) %>
      </li>

    </ul>
    <% if @recently_viewed.present?  %>
      <ul id="recent-activity" class="list-group">
        <li class="list-group-item first">Recently Viewed</li>
        <% @recently_viewed.each do |pageview| %>
          <% page = pageview.page %>
          <li class="list-group-item">
            <div class="media">
              <%= link_to (image_tag page.cover_photo(:thumb)), page.slug_path, :class => "pull-left", :alt => page.title %>
                <div class="media-body">
                  <h3 class="media-heading"><%= page.title %></h3>
                  <p>
                    <%= about_page_trunc(page) %>
                  </p>
                </div>
                <span><%= link_to "#{page.likes_count} likes", page.slug_path, :class => "special-hover-link" %></span>
              </div>
          </li>
        <% end %>
      </ul>
    <% end %>
    
</div>
      